#!/usr/bin/env node
require("traceur");
require("sugar");
Object.extend();
var values = {
  "A": 11,
  "J": 10,
  "Q": 10,
  "K": 10
},
    ranks = {
      "ace": "A",
      "two": 2,
      "three": 3,
      "four": 4,
      "five": 5,
      "six": 6,
      "seven": 7,
      "eight": 8,
      "nine": 9,
      "ten": 10,
      "jack": "J",
      "queen": "Q",
      "king": "K"
    };
var Card = function Card(str) {
  "use strict";
  this.rank = ranks[$traceurRuntime.toProperty(str.toLowerCase().words()[0])];
};
($traceurRuntime.createClass)(Card, {get value() {
    "use strict";
    return values[$traceurRuntime.toProperty(this.rank)] || this.rank;
  }}, {});
var Player = function Player(str) {
  "use strict";
  var split = str.split(": ");
  this.name = split[0];
  this.cards = split[1].split(", ").map((function(c) {
    return new Card(c);
  }));
};
($traceurRuntime.createClass)(Player, {get value() {
    "use strict";
    var aces = this.cards.filter((function(c) {
      return c.rank == "A";
    })).length;
    var retval = this.cards.reduce((function(p, c) {
      return p += c.value;
    }), 0);
    for (; aces > 0 && retval > 21; aces--) {
      retval -= 10;
    }
    return retval > 21 ? 0 : (this.cards.length > 4 ? 99 : retval);
  }}, {});
var res = require("fs").readFileSync(process.argv[2]).toString().lines().slice(1).filter((function(line) {
  return line.has(":");
})).each((function(line) {
  return console.log(line);
})).map((function(line) {
  return new Player(line);
})).sortBy("value").reverse();
if (!res[0].value) {
  console.log("Everyone busted. Good job.");
} else if (res.length > 2 && res[0].value == res[1].value && res[1].value == res[2].value) {
  console.log("A bunch of people tied.");
} else if (res[0].value == res[1].value) {
  console.log("{1} and {2} tied.".assign(res[0].name, res[1].name));
} else if (res[0].value == 99) {
  console.log("{1} wins with a five-card trick!".assign(res[0].name));
} else if (res[0].value == 21) {
  console.log("{1} wins with Blackjack!".assign(res[0].name));
} else {
  console.log("{1} wins with {2}.".assign(res[0].name, res[0].value));
}
