#!/bin/bash
# Compiles ES6 to ES5, adds traceur and sugar (w/ Object.extend()),
# adds the crunchbang for node, and makes executable.
ARGS=("--experimental" "--out" "es6.cmp.js")
for a in "$@"; do ARGS+=("--script" "$a"); done
[[ $# -lt 1 ]] && ARGS+=("--script" "es6.js")
traceur "${ARGS[@]}"
sed -i '1s:^:#!/usr/bin/env node\nrequire("traceur");require("sugar");Object.extend();\n:' es6.cmp.js
chmod +x es6.cmp.js
mv es6.cmp.js es6.cmp
