#!/bin/bash
# Compiles ES6 to ES5, adds #! for node, requires traceur, and makes executable.
set -e
OUT="es6.cmp"
while getopts "o:" OPT; do case "$OPT" in
    o) OUT="$OPTARG" ;;
esac; done
shift $((OPTIND-1))
DIR=$(dirname $(readlink -f "$0"))
ARGS=("--experimental" "--out" "$OUT.js")
for a in "$@"; do ARGS+=("--script" "$a"); done
[[ $# -lt 1 ]] && ARGS+=("--script" "es6.js")
"$DIR/node_modules/traceur/traceur" "${ARGS[@]}"
sed -i '1s:^:#!/usr/bin/env node\nrequire("traceur");\n:' "$OUT.js"
chmod +x "$OUT.js"
mv "$OUT.js" "$OUT"
