#!/usr/bin/env node
require("traceur");
require("sugar");
var n = parseInt(process.argv[2]);
console.log("Calculating sequence to iteration %s.", n);
var seq = [false];
n.times((function() {
  return seq.add(seq.map((function(item) {
    return !item;
  })));
}));
console.log(seq.map((function(item) {
  return item ? 1 : 0;
})).join(""));
